#Text file of sample name list
samples: "rodent_oral_data_list.txt" 

#Directory to Fastq files, path/to/directory
fastq_dir: "fastq_data" 

#Path/to/bowtie_index
bowtie_index: "combined_ref_genomes/rat_shrew_genome" 
